// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 应用服务 — 所有 Wails 前端绑定方法集中在此
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CleanupClipboardNow(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2613197776);
}

export function CopyClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2791837413, id);
}

export function CreateCollection(workspaceID: string, sceneID: string, name: string, collType: string, openStrategy: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2067640298, workspaceID, sceneID, name, collType, openStrategy);
}

export function CreateItem(workspaceID: string, collectionID: string, name: string, itemType: string, value: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1125639857, workspaceID, collectionID, name, itemType, value);
}

export function CreateScene(workspaceID: string, name: string, sceneType: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1525519562, workspaceID, name, sceneType);
}

export function CreateSnapshot(label: string, note: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(380947062, label, note);
}

export function CreateSnippet(keyword: string, content: string, category: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3593801203, keyword, content, category);
}

export function CreateTool(name: string, toolType: string, path: string, args: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3719376436, name, toolType, path, args);
}

export function CreateWorkspace(name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3835056875, name);
}

export function DeleteClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3873629203, id);
}

export function DeleteCollection(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3367188829, id);
}

export function DeleteExpiredClipboardEntries(): $CancellablePromise<number> {
    return $Call.ByID(593592192);
}

export function DeleteItem(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1723196642, id);
}

export function DeleteScene(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2723283319, id);
}

export function DeleteSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4064953593, id);
}

export function DeleteSnippet(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1222531986, id);
}

export function DeleteWorkspace(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1133673306, id);
}

/**
 * ExecuteSystemCommand executes a system command (lock/shutdown/restart/sleep/emptytrash)
 */
export function ExecuteSystemCommand(cmd: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(289709581, cmd);
}

export function GetAutoStart(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3655302239);
}

export function GetClipboardHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(959596256);
}

/**
 * GetClipboardImageBase64 获取剪贴板图片的 base64 数据 URI
 */
export function GetClipboardImageBase64(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2529797502, id);
}

export function GetClipboardRetentionDays(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2386759077);
}

export function GetHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2024743010);
}

/**
 * GetLastCopiedText 返回最近一次复制的文本
 */
export function GetLastCopiedText(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4290356633);
}

/**
 * GetMostUsedItems 返回最常使用的项目（命令面板「最近使用」）
 */
export function GetMostUsedItems(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(174226976, limit);
}

export function GetPaletteHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2693772577);
}

export function GetSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1988116934, id);
}

/**
 * GetValue 读取键值
 */
export function GetValue(key: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3622336851, key);
}

/**
 * GetWebDAVConfig 获取 WebDAV 同步配置
 */
export function GetWebDAVConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2832353333);
}

export function GetWorkspace(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2311531739, id);
}

/**
 * HideClipboardWindow 隐藏剪贴板独立窗口
 */
export function HideClipboardWindow(): $CancellablePromise<void> {
    return $Call.ByID(2624956500);
}

/**
 * HidePaletteWindow 隐藏命令面板窗口
 */
export function HidePaletteWindow(): $CancellablePromise<void> {
    return $Call.ByID(1149548777);
}

/**
 * HideWindow 隐藏主窗口
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(360771842);
}

export function InsertClipboardEntry(text: string, sourceApp: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2229753297, text, sourceApp);
}

/**
 * LaunchInstalledApp 启动指定路径的应用
 */
export function LaunchInstalledApp(path: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2257915428, path);
}

export function ListClipboardEntries(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2291752860);
}

export function ListCollections(sceneID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1896706667, sceneID);
}

export function ListItems(collectionID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3764977142, collectionID);
}

export function ListScenes(workspaceID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3351845611, workspaceID);
}

export function ListSnapshots(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1489806735);
}

export function ListSnippets(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1439974928);
}

export function ListTools(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1665311253);
}

export function ListWorkspaces(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1048839064);
}

/**
 * OnClipboardChange handles clipboard change events
 */
export function OnClipboardChange(): $CancellablePromise<void> {
    return $Call.ByID(2121315099);
}

export function OpenAllInCollection(collectionID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1237590910, collectionID);
}

export function OpenItem(item: db$0.CollectionItem): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(59138333, item);
}

/**
 * PasteClipboardEntry 复制剪贴板条目并模拟 Ctrl+V 粘贴
 */
export function PasteClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2364851955, id);
}

/**
 * PasteSnippet 将片段内容复制到剪贴板并粘贴
 */
export function PasteSnippet(content: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2289619634, content);
}

export function ReorderCollections(orderedIDs: string[] | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1456313334, orderedIDs);
}

export function ReorderItems(orderedIDs: string[] | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1523637631, orderedIDs);
}

export function ReorderScenes(orderedIDs: string[] | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4156556976, orderedIDs);
}

export function ReorderWorkspaces(orderedIDs: string[] | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3135663759, orderedIDs);
}

/**
 * ResetInstalledAppsCache 清除应用缓存（下次搜索时重新扫描）
 */
export function ResetInstalledAppsCache(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(421562045);
}

export function RestoreSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2330421416, id);
}

export function ResumeHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(469208180);
}

/**
 * ScanInstalledApps 扫描已安装应用（缓存，首次调用后复用）
 */
export function ScanInstalledApps(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2397186455);
}

/**
 * SearchAll 跨全部工作空间搜索项目（使用 FTS5）
 */
export function SearchAll(query: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1354570973, query);
}

export function SearchSnippets(query: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1489427676, query);
}

/**
 * SetApp 设置 App 引用（由 main.go 在创建后调用）
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3735478509, app);
}

export function SetAutoStart(enabled: boolean): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1650346907, enabled);
}

export function SetClipboardHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2903533492, modifiers, vk);
}

export function SetClipboardRetentionDays(days: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3284935865, days);
}

export function SetHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3895446934, modifiers, vk);
}

export function SetPaletteHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(189880149, modifiers, vk);
}

/**
 * SetValue 写入键值
 */
export function SetValue(key: string, value: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3540985191, key, value);
}

/**
 * SetWebDAVConfig 保存 WebDAV 同步配置
 */
export function SetWebDAVConfig(config: $models.WebDAVConfig | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1434230337, config);
}

export function SuspendHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(1551644173);
}

export function TogglePinClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1629693783, id);
}

export function UpdateCollection(id: string, updates: { [_ in string]?: any } | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2047807399, id, updates);
}

export function UpdateItem(id: string, updates: { [_ in string]?: any } | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3624550944, id, updates);
}

export function UpdateScene(id: string, updates: { [_ in string]?: any } | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(688719653, id, updates);
}

export function UpdateWorkspace(id: string, name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1525445244, id, name);
}

/**
 * WebDAVDeleteBackup 删除 WebDAV 上的备份文件
 */
export function WebDAVDeleteBackup(filename: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(284342406, filename);
}

/**
 * WebDAVDownaloadAndRestore 从 WebDAV 下载备份并恢复到数据库
 */
export function WebDAVDownaloadAndRestore(filename: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3490539115, filename);
}

/**
 * WebDAVExportBackup 导出当前数据并上传到 WebDAV
 */
export function WebDAVExportBackup(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1282091347);
}

/**
 * WebDAVListBackups 列出 WebDAV 服务器上的备份文件
 */
export function WebDAVListBackups(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1768986214);
}

/**
 * WebDAVTestConnection 测试 WebDAV 连接
 */
export function WebDAVTestConnection(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2416182375);
}
