// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApiResult 统一 API 返回结构
 * code: 0=成功, 1=失败
 */
export interface ApiResult {
    "code": number;
    "data": any;
    "msg": string;
}

/**
 * WebDAVConfig WebDAV 同步配置
 */
export interface WebDAVConfig {
    "url": string;
    "username": string;
    "password": string;
}
