// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIConfig 兼容旧接口的单一配置（API Key 已解密）
 */
export interface AIConfig {
    "provider": string;
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "temperature": number;
    "maxTokens": number;
}

/**
 * AIProfile 一个完整的 AI 配置档案（含 API Key，前端回填时为明文）
 */
export interface AIProfile {
    "id": string;
    "name": string;
    "provider": string;
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "temperature": number;
    "maxTokens": number;
    "systemPrompt": string;
    "topP": number;
    "frequencyPenalty": number;
    "presencePenalty": number;
    "thinkingEnabled": boolean;
}

/**
 * AISaveProfilesRequest 保存档案列表的请求
 */
export interface AISaveProfilesRequest {
    "active": string;
    "profiles": AIProfile[] | null;
}

/**
 * ApiResult 统一 API 返回结构
 * code: 0=成功, 1=失败
 */
export interface ApiResult {
    "code": number;
    "data": any;
    "msg": string;
}

/**
 * UpdateStatus 返回给前端的更新状态
 */
export interface UpdateStatus {
    "currentVersion": string;

    /**
     * idle / checking / available / up-to-date / downloading / ready / error
     */
    "state": string;
    "availableVersion"?: string;
    "releaseNotes"?: string;

    /**
     * 0-100
     */
    "downloadProgress"?: number;
    "error"?: string;
}

/**
 * WebDAVConfig WebDAV 同步配置
 */
export interface WebDAVConfig {
    "url": string;
    "username": string;
    "password": string;
}
