// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionItem 项目
 */
export interface CollectionItem {
    "id": string;
    "workspaceId": string;
    "collectionId": string;
    "name": string;
    "type": string;
    "value": string;
    "workingDirectory": string;
    "toolId": string;
    "tool": string;
    "args": string;
    "icon": string;
    "color": string;
    "remark": string;
    "pluginData": string;
    "usageCount": number;
    "sort": number;
    "createdAt": string;
    "updatedAt": string;
}
