package env

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"

	"quickdock/internal/logger"
	"quickdock/internal/platform"
)

const redisBaseRel = "runtime/redis"

const redisDefaultPort = 6379

// redisPortRe 解析 redis.conf 中的 "port 6379" 指令。
var redisPortRe = regexp.MustCompile(`(?i)^\s*port\s+(\d+)\s*$`)

// RedisConfig 某 Redis 版本的配置快照（redis.conf 全文，供前端编辑）。
type RedisConfig struct {
	Path string `json:"path"` // redis.conf 绝对路径
	Raw  string `json:"raw"`  // redis.conf 全文
}

// defaultRedisConf 首次安装/缺失时写入的默认配置：仅监听本地回环、持久化目录为版本目录、
// 日志走 stdout（由 QuickDock 捕获落盘到 redis.log，故不设置 logfile）。
const defaultRedisConf = `# Generated by QuickDock
bind 127.0.0.1
port 6379
dir ./
databases 16
save 900 1
save 300 10
save 60 10000
# logfile ""  # 注释掉：日志输出到 stdout，由 QuickDock 捕获写入 redis.log
`

// RedisRuntime 管理便携 Redis 运行时（tporadowski/redis Windows 构建），多版本共存于 runtime/redis/<version>。
// 同时实现 ServiceController，支持以服务方式启动/停止并监听运行状态。
type RedisRuntime struct {
	baseDir string
}

func NewRedisRuntime() *RedisRuntime {
	return &RedisRuntime{baseDir: filepath.Join(platform.DefaultDataDir(), redisBaseRel)}
}

func (r *RedisRuntime) Kind() Runtime                 { return RuntimeRedis }
func (r *RedisRuntime) DetectArgs() []string          { return []string{"--version"} }
func (r *RedisRuntime) ParseVersion(out string) (string, error) {
	if v := parseRedisVersion(out); v != "" {
		return v, nil
	}
	return "", fmt.Errorf("无法识别 %s 版本", DisplayName(RuntimeRedis))
}
func (r *RedisRuntime) DisplayName() string          { return DisplayName(RuntimeRedis) }
func (r *RedisRuntime) SupportedPlatforms() []string { return []string{"windows"} }
func (r *RedisRuntime) Recommended() []string        { return Versions(RuntimeRedis) }

func (r *RedisRuntime) versionDir(version string) string {
	return filepath.Join(r.baseDir, version)
}

func (r *RedisRuntime) ExeFor(version string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(r.versionDir(version), "redis-server.exe")
	}
	return filepath.Join(r.versionDir(version), "redis-server")
}

func (r *RedisRuntime) InstalledVersions() []Install {
	var out []Install
	dirs := managedDirs{}
	if entries, err := os.ReadDir(r.baseDir); err == nil {
		for _, e := range entries {
			if !e.IsDir() {
				continue
			}
			v := e.Name()
			if _, err := os.Stat(r.ExeFor(v)); err == nil {
				out = append(out, Install{Version: v, Scope: "portable", Path: r.versionDir(v)})
				dirs.record(filepath.Dir(r.ExeFor(v)))
			}
		}
	}
	if exe, err := exec.LookPath("redis-server"); err == nil {
		if v := parseRedisVersion(RunVersion(exe, "--version")); v != "" {
			// LookPath 命中本就由 QuickDock 托管并写入 PATH 的便携版时，不再重复登记为 system。
			if dirs.dedupeByDir(exe) {
				return out
			}
			out = append(out, Install{Version: v, Scope: "system", Path: exe})
		}
	}
	return out
}

// DeleteVersion 删除某便携 Redis 版本目录（系统 PATH 上的版本无目录可删，返回错误）。
func (r *RedisRuntime) DeleteVersion(version string) error {
	dir := r.versionDir(version)
	if _, err := os.Stat(dir); err != nil {
		return fmt.Errorf("未找到该版本: %s", version)
	}
	return os.RemoveAll(dir)
}

func (r *RedisRuntime) Install(ctx context.Context, version string, cb InstallCallback) error {
	if version == "" {
		version = Versions(RuntimeRedis)[0]
	}
	dir := r.versionDir(version)
	if _, err := os.Stat(r.ExeFor(version)); err == nil {
		if cb.OnLog != nil {
			cb.OnLog("Redis " + version + " 已安装: " + r.ExeFor(version))
		}
		return nil
	}
	if _, err := os.Stat(dir); err == nil {
		os.RemoveAll(dir)
	}
	urls := CandidateURLs(RuntimeRedis, version)
	if len(urls) == 0 {
		return fmt.Errorf("无可用 Redis 下载源")
	}
	zipPath := filepath.Join(os.TempDir(), "quickdock-redis-"+version+".zip")
	if cb.OnStage != nil {
		cb.OnStage("download", "正在下载 Redis "+version+"…")
	}
	if cb.OnLog != nil {
		cb.OnLog("正在下载 Redis " + version + "…")
	}
	if err := Download(ctx, zipPath, urls, cb.OnProgress); err != nil {
		return fmt.Errorf("下载 Redis 失败: %w", err)
	}
	defer os.Remove(zipPath)
	if cb.OnStage != nil {
		cb.OnStage("extract", "正在解压 Redis…")
	}
	if cb.OnLog != nil {
		cb.OnLog("解压 Redis 到 " + dir)
	}
	if err := Extract(zipPath, dir); err != nil {
		return fmt.Errorf("解压 Redis 失败: %w", err)
	}
	if _, err := os.Stat(r.ExeFor(version)); err != nil {
		return fmt.Errorf("解压完成但未找到 %s", r.ExeFor(version))
	}
	// 生成默认 redis.conf（若缺失），保证「配置设置」功能开箱可用
	if err := r.ensureConfig(version); err != nil {
		return fmt.Errorf("生成 redis.conf 失败: %w", err)
	}
	if cb.OnLog != nil {
		cb.OnLog("Redis " + version + " 解压完成")
	}
	return nil
}

// ---- ServiceController ----

func (r *RedisRuntime) DefaultPort() int { return redisDefaultPort }

func (r *RedisRuntime) Start(ctx context.Context, version string, onLog func(string)) error {
	installs := r.InstalledVersions()
	if version == "" {
		if len(installs) == 0 {
			return fmt.Errorf("请先安装 Redis 版本")
		}
		version = installs[0].Version
	}
	logger.I("[env][redis] Start 请求 version=%s 已安装=%v", version, installVersionsLog(installs))
	// 系统 PATH 上的版本 Path 本身就是 redis-server.exe；便携版本走 adapter.ExeFor。
	// 之前硬走 r.ExeFor(version) → 系统安装时 stat 不到报「未安装该版本」。
	var exe, wd, scope string
	for _, ins := range installs {
		if ins.Version != version {
			continue
		}
		if ins.Scope == "system" {
			exe, wd, scope = ins.Path, filepath.Dir(ins.Path), "system"
		} else {
			exe, wd, scope = r.ExeFor(version), r.versionDir(version), "portable"
		}
		break
	}
	if exe == "" {
		logger.E("[env][redis] Start 失败：未找到已安装版本 %s", version)
		return fmt.Errorf("未安装该版本: %s", version)
	}
	if _, err := os.Stat(exe); err != nil {
		logger.E("[env][redis] Start 失败：exe 不存在 %s err=%v", exe, err)
		return fmt.Errorf("未安装该版本: %s", version)
	}
	// 多版本共用默认端口：已在运行其它版本时，明确提示先停止，避免误以为能并行跑两个实例
	running, _ := svcMgr.info(RuntimeRedis)
	if running != "" && running != version {
		logger.W("[env][redis] Start 拒绝：Redis 已在运行（%s），请求启动 %s", running, version)
		return fmt.Errorf("Redis 已在运行（%s），请先停止当前版本再启动 %s", running, version)
	}
	// 端口被本机其它程序占用（非本会话拉起）时，bind 会短暂误报 running，这里提前给清晰提示
	port := r.configPort(version)
	if running == "" && isPortOpen(port) {
		logger.W("[env][redis] Start 拒绝：端口 %d 已被占用（可能是其它程序），无法启动 %s", port, version)
		return fmt.Errorf("端口 %d 已被占用，请先释放该端口或更改 Redis 配置端口", port)
	}
	if onLog != nil {
		onLog("启动 Redis " + version + " …")
	}
	// 便携版本：以 redis.conf 启动（相对路径，redis 按 cwd=版本目录解析），并把输出落盘到 redis.log 供日志查询。
	// 系统 PATH 版本无托管目录，无法落配置文件/日志，直接裸启动。
	if scope == "system" {
		logger.I("[env][redis] 以系统 PATH 版本启动 exe=%s wd=%s scope=system", exe, wd)
		return svcMgr.start(RuntimeRedis, version, exe, wd, nil, "", onLog)
	}
	if err := r.ensureConfig(version); err != nil {
		logger.E("[env][redis] 生成 redis.conf 失败 version=%s err=%v", version, err)
		return fmt.Errorf("生成 redis.conf 失败: %w", err)
	}
	logger.I("[env][redis] 以便携版本启动 exe=%s wd=%s scope=portable conf=redis.conf log=%s", exe, wd, r.LogPath(version))
	return svcMgr.start(RuntimeRedis, version, exe, wd, []string{"redis.conf"}, r.LogPath(version), onLog)
}

// installVersionsLog 仅用于日志：把已安装版本列表压成短串。
func installVersionsLog(installs []Install) string {
	parts := make([]string, 0, len(installs))
	for _, ins := range installs {
		parts = append(parts, ins.Version+"("+ins.Scope+")")
	}
	return strings.Join(parts, ",")
}

// ConfigPath 返回某版本 redis.conf 绝对路径。
func (r *RedisRuntime) ConfigPath(version string) string {
	return filepath.Join(r.versionDir(version), "redis.conf")
}

// LogPath 返回某版本 redis.log 绝对路径（运行日志落盘位置）。
func (r *RedisRuntime) LogPath(version string) string {
	return filepath.Join(r.versionDir(version), "redis.log")
}

// ensureConfig 默认配置缺失时写入一份默认 redis.conf。
func (r *RedisRuntime) ensureConfig(version string) error {
	p := r.ConfigPath(version)
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return os.WriteFile(p, []byte(defaultRedisConf), 0644)
}

// ConfigGet 读取某版本的 redis.conf 配置。
func (r *RedisRuntime) ConfigGet(version string) (*RedisConfig, error) {
	if version == "" {
		return nil, fmt.Errorf("版本为空")
	}
	p := r.ConfigPath(version)
	if _, err := os.Stat(p); err != nil {
		// 配置缺失时尝试生成默认配置，保证前端总能打开编辑
		if err := r.ensureConfig(version); err != nil {
			return nil, err
		}
	}
	data, err := os.ReadFile(p)
	if err != nil {
		return nil, err
	}
	return &RedisConfig{Path: p, Raw: string(data)}, nil
}

// ConfigSet 写回某版本的 redis.conf（整体覆盖）。
func (r *RedisRuntime) ConfigSet(version, raw string) error {
	if version == "" {
		return fmt.Errorf("版本为空")
	}
	if strings.TrimSpace(raw) == "" {
		return fmt.Errorf("配置内容为空")
	}
	return os.WriteFile(r.ConfigPath(version), []byte(raw), 0644)
}

// LogGet 读取某版本的 redis.log 尾部内容（最多 8KB）供日志查询。
func (r *RedisRuntime) LogGet(version string) (string, error) {
	if version == "" {
		return "", fmt.Errorf("版本为空")
	}
	data, err := os.ReadFile(r.LogPath(version))
	if err != nil {
		return "", err
	}
	if len(data) > 8192 {
		data = data[len(data)-8192:]
	}
	return strings.TrimSpace(string(data)), nil
}

// configPort 从 redis.conf 中解析 port 指令（解析失败回退默认端口）。
func (r *RedisRuntime) configPort(version string) int {
	data, err := os.ReadFile(r.ConfigPath(version))
	if err != nil {
		return redisDefaultPort
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "#") {
			continue
		}
		if m := redisPortRe.FindStringSubmatch(line); m != nil {
			if p, e := strconv.Atoi(m[1]); e == nil && p > 0 {
				return p
			}
		}
	}
	return redisDefaultPort
}

func (r *RedisRuntime) Stop(version string) error {
	logger.I("[env][redis] Stop 请求 version=%s", version)
	// 端口取自该版本 redis.conf 的 port 指令（解析失败回退默认），支持用户自定义端口；
	// 此前写死 6379 会导致改端口后关不掉真实实例、还可能误杀占用 6379 的无关 redis。
	port := r.configPort(version)
	// 1) 对每个已装版本目录尝试原生优雅关闭（redis-cli SHUTDOWN NOSAVE，覆盖孤儿/多版本）
	for _, ins := range r.InstalledVersions() {
		runRedisStopSignal(filepath.Join(r.versionDir(ins.Version), "redis-cli.exe"), port)
	}
	// 2) 端口兜底：杀掉占用该端口且镜像确为 redis-server.exe 的进程树
	stopByPort(port, "redis-server.exe")
	// 3) 清掉会话内记录的句柄
	svcMgr.forget(RuntimeRedis)
	logger.I("[env][redis] Stop 完成 version=%s port=%d", version, port)
	return nil
}

// runningVersion 返回当前（该 version 配置端口上）实际在跑的 Redis 版本；无运行返回 ""。
// 优先用本会话拉起的句柄（最准确），否则按监听进程的可执行文件路径反查到具体版本目录。
// 端口取自 redis.conf 的 port 指令（解析失败回退默认），从而支持用户在配置中修改端口。
func (r *RedisRuntime) runningVersion(version string) string {
	port := r.configPort(version)
	if v, _ := svcMgr.info(RuntimeRedis); v != "" {
		return v
	}
	if !isPortOpen(port) {
		return ""
	}
	pid := findListenPID(port)
	if pid == 0 {
		return ""
	}
	exe := processExePath(pid)
	if exe == "" {
		return ""
	}
	for _, ins := range r.InstalledVersions() {
		target := ins.Path
		if ins.Scope == "portable" {
			target = r.ExeFor(ins.Version)
		}
		if strings.EqualFold(exe, target) {
			return ins.Version
		}
	}
	return ""
}

func (r *RedisRuntime) Status(version string) ServiceStatus {
	port := r.configPort(version)
	st := ServiceStatus{Running: false, Port: port}
	// 仅当实际运行的版本就是本次查询的版本时才标记运行中，避免多版本互相串状态
	if r.runningVersion(version) == version {
		st.Running = true
		st.Version = version
		st.PID = svcMgr.pid(RuntimeRedis)
		if st.PID == 0 {
			st.PID = findListenPID(port)
		}
	}
	return st
}

func parseRedisVersion(out string) string {
	// "Redis server v=5.0.14.1 sha=... malloc=jemalloc ..."
	for _, tok := range strings.Fields(out) {
		if strings.HasPrefix(tok, "v=") {
			return strings.TrimPrefix(tok, "v=")
		}
	}
	return ""
}
