// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 应用服务 — 所有 Wails 前端绑定方法集中在此
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../internal/sync/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AIClearMessages 清空某会话的上下文（消息与摘要）
 */
export function AIClearMessages(convID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3444167825, convID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AICreateConversation 新建会话
 */
export function AICreateConversation(title: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(308772527, title).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIDeleteConversation 删除会话
 */
export function AIDeleteConversation(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3073238696, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIGetConfig 兼容旧接口：返回当前激活档案（API Key 以掩码形式返回）
 */
export function AIGetConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1566209782).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIGetMessages 读取某会话的消息
 */
export function AIGetMessages(convID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3385408564, convID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIListConversations 列出会话
 */
export function AIListConversations(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1634142192).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIListProfiles 列出所有档案（API Key 已解密）与当前激活项
 */
export function AIListProfiles(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1812690326).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIRegenerateTitle 调用模型，根据对话内容生成短标题
 */
export function AIRegenerateTitle(convID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4028519516, convID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AISaveProfiles 保存完整档案列表与激活项（API Key 留空则保留原密文）
 */
export function AISaveProfiles(req: $models.AISaveProfilesRequest): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3153383435, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AISetActiveProfile 设置当前激活的档案（聊天中切换模型用）
 */
export function AISetActiveProfile(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3702274987, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AISetConfig 兼容旧接口：写入单个默认档案
 */
export function AISetConfig(cfg: $models.AIConfig): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4144179170, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AIStreamInfo 返回本地 AI 流式服务的端口与随机令牌。
 */
export function AIStreamInfo(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(799378472).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AITestConnection(profileID: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3906599712, profileID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ApplyTheme 将 App 主题应用到所有原生窗口：
 *   - 主窗口（Frameless:false，系统原生标题栏）：通过 DWM 沉浸式暗色模式让标题栏
 *     跟随 App 主题（浅色下不再发黑）。
 *   - 插件窗口（Frameless:true）：原生标题栏不存在，只需让窗口底色跟随主题，
 *     消除内容未填满时露出的黑底；同时记录到 PluginWindowMgr 供后续新建窗口沿用。
 * 
 * 由前端 App.vue 在挂载与切换主题时调用。
 */
export function ApplyTheme(isDark: boolean): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2655001727, isDark).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BuildCurlCommand 把请求转成 curl 命令字符串（已应用环境变量替换、认证、header 与 body）。
 * 供前端一键复制。
 */
export function BuildCurlCommand(input: $models.ApiRequestInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(916967473, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckForUpdates 手动检查更新（阻塞直到检查完成）。与后台定时检查共用 runCheck。
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateStatus | null> {
    return $Call.ByID(3257391909).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CheckMonitorNow 立即手动检测一次（不影响下次调度）
 */
export function CheckMonitorNow(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3374015592, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CleanupClipboardNow(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2613197776).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearClipboardHistory 清空剪贴板历史（保留固定的条目）
 */
export function ClearClipboardHistory(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(521484201).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearCompletedTodos 清除已完成项
 */
export function ClearCompletedTodos(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3023679065).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearHttpHistory 清空某项目（projectID 为空=全部）的历史。
 */
export function ClearHttpHistory(projectID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1177539809, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearMonitorLogs 清空某监控的检测日志
 */
export function ClearMonitorLogs(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2018514900, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CopyClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2791837413, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CopyText 将文本写入系统剪贴板（命令面板结果复制用）。
 * 直接走 Wails Clipboard.SetText，避免 WebView2 中 navigator.clipboard
 * 在文档未聚焦时被静默拦截的问题。
 */
export function CopyText(text: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2595923732, text).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateApiRequest 保存新请求，返回带 ID 的记录。
 */
export function CreateApiRequest(input: $models.ApiRequestInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(345996275, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateCollection(workspaceID: string, sceneID: string, name: string, collType: string, openStrategy: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2067640298, workspaceID, sceneID, name, collType, openStrategy).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateHttpDoc 新建文档。
 */
export function CreateHttpDoc(input: $models.HttpDocInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3563829308, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateHttpEnvironment 新建环境。
 */
export function CreateHttpEnvironment(input: $models.HttpEnvInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1682453295, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateHttpFolder 新建目录。
 */
export function CreateHttpFolder(input: $models.HttpFolderInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2923689114, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateHttpProject 新建项目。
 */
export function CreateHttpProject(input: $models.HttpProjectInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(131940339, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateItem(workspaceID: string, collectionID: string, name: string, itemType: string, value: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1125639857, workspaceID, collectionID, name, itemType, value).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateMonitor 新建网站监控
 */
export function CreateMonitor(m: db$0.Monitor): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3784597404, m).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateNoteDoc 新建笔记文档（Markdown/纯文本）。parentId 可为空（根）。
 */
export function CreateNoteDoc(parentId: string, name: string, content: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3205648792, parentId, name, content).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateNoteFolder 新建文件夹。
 */
export function CreateNoteFolder(parentId: string, name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3018504886, parentId, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateScene(workspaceID: string, name: string, sceneType: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1525519562, workspaceID, name, sceneType).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateScheduledTask 新建定时任务，next_run 由后端根据调度规则计算
 */
export function CreateScheduledTask(t: db$0.ScheduledTask): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1896217520, t).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSnapshot(label: string, note: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(380947062, label, note).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSnippet(keyword: string, content: string, category: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3593801203, keyword, content, category).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateSubtask 新建子任务（归属指定父待办）
 */
export function CreateSubtask(parentID: string, title: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1524722157, parentID, title).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTodo 新建待办（含起止时间、提醒时间、标签与重复配置）
 */
export function CreateTodo(title: string, priority: string, dueDate: string, note: string, startTime: string, endTime: string, reminderTime: string, recurrence: string, tags: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3234546698, title, priority, dueDate, note, startTime, endTime, reminderTime, recurrence, tags).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateTool(name: string, toolType: string, path: string, args: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3719376436, name, toolType, path, args).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateWorkspace(name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3835056875, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteApiRequest 删除保存的请求。
 */
export function DeleteApiRequest(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2484648156, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3873629203, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteCollection(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3367188829, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteDbConnection 删除连接。
 */
export function DeleteDbConnection(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2884817991, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteExpiredClipboardEntries(): $CancellablePromise<number> {
    return $Call.ByID(593592192);
}

/**
 * DeleteHttpDoc 删除文档。
 */
export function DeleteHttpDoc(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1535475121, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteHttpEnvironment 删除环境。
 */
export function DeleteHttpEnvironment(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3566187614, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteHttpFolder 删除目录（级联删除子目录与请求）。
 */
export function DeleteHttpFolder(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2341811273, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteHttpHistory 删除一条历史。
 */
export function DeleteHttpHistory(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2712980571, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteHttpProject 删除项目（其下请求回退未分类，环境级联删除）。
 */
export function DeleteHttpProject(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2233360802, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteItem(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1723196642, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteMonitor 删除监控及其日志
 */
export function DeleteMonitor(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(509872029, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteNoteNode 递归删除节点及其子树。
 */
export function DeleteNoteNode(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(658624809, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteScene(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2723283319, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteScheduledTask 删除定时任务
 */
export function DeleteScheduledTask(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3509442289, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4064953593, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteSnippet(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1222531986, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteTodo 删除待办（同时清理其重复调度记录）
 */
export function DeleteTodo(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(775653569, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTool(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(758037307, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteWorkspace(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1133673306, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DisablePlugin(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3188936753, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadUpdate 下载发现的更新（阻塞直到下载完成）
 */
export function DownloadUpdate(): $CancellablePromise<$models.UpdateStatus | null> {
    return $Call.ByID(2223297711).then(($result: any) => {
        return $$createType4($result);
    });
}

export function EnablePlugin(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2515910434, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExecutePluginCommand(pluginID: string, commandID: string, input: { [_ in string]?: any }): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1257077587, pluginID, commandID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteSystemCommand executes a system command (lock/shutdown/restart/sleep/emptytrash)
 */
export function ExecuteSystemCommand(cmd: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(289709581, cmd).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportClipboard 导出全部剪贴板历史为 JSON 数组（图片条目含 base64，前端可下载为文件）
 */
export function ExportClipboard(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3647578146).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAllUsage 返回全部 frecency 记录（前端初始化一次性加载）
 */
export function GetAllUsage(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4257927220).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAndClearPendingPluginInit 取出并清除待注入的初始文本和命令
 */
export function GetAndClearPendingPluginInit(): $CancellablePromise<[string, string]> {
    return $Call.ByID(2879713414);
}

/**
 * GetAppVersion 返回当前应用版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3689300579);
}

export function GetAutoStart(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3655302239).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetClipboardHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(959596256).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetClipboardImageBase64 获取剪贴板图片的 base64 数据 URI
 */
export function GetClipboardImageBase64(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2529797502, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetClipboardRetentionDays(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2386759077).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2024743010).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetHttpHistoryAsApiRequest 把一条历史还原成 ApiRequestInput（供"重放/载入表单"）。
 * 返回 (input, error)；未找到返回 (nil, fmt.Errorf())。用 string 避免 ApiResult 双层封装。
 */
export function GetHttpHistoryAsApiRequest(id: string): $CancellablePromise<[$models.ApiRequestInput | null, string]> {
    return $Call.ByID(3833431367, id).then(($result: any) => {
        $result[0] = $$createType6($result[0]);
        return $result;
    });
}

/**
 * GetLastCopiedText 返回最近一次复制的文本
 */
export function GetLastCopiedText(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4290356633).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMonitorLogs 返回某监控最近 limit 条检测日志
 */
export function GetMonitorLogs(id: string, limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3720800551, id, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMonitorLogsSince 返回某监控 checked_ts >= sinceTs 的检测日志（时间范围切换用）
 */
export function GetMonitorLogsSince(id: string, sinceTs: number, limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2587060783, id, sinceTs, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMostUsedItems 返回最常使用的项目（命令面板「最近使用」）
 */
export function GetMostUsedItems(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(174226976, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetNote 读取快捷笔记内容（find-or-create 固定关键词片段）
 */
export function GetNote(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1516142134).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetNoteHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2040649190).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPaletteHotkeyConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2693772577).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPluginFrontendPage 获取插件前端页面（内联 CSS/JS 的单 HTML 文件）
 */
export function GetPluginFrontendPage(pluginID: string, theme: string, locale: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2755477758, pluginID, theme, locale).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPluginFrontendURL(pluginID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2407518182, pluginID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPluginIcon 获取插件图标（返回 base64 data URI）
 */
export function GetPluginIcon(pluginID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2284800544, pluginID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetRecentUsage 返回最近使用的 N 条记录（命令面板「最近使用」专用）
 */
export function GetRecentUsage(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2751728964, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1988116934, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSnippetByKeyword 按关键词查询片段（快捷笔记用）
 */
export function GetSnippetByKeyword(keyword: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3971639549, keyword).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSyncConfig 获取统一同步配置（密码为明文，供 UI 回填）。
 */
export function GetSyncConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3850252451).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTopUsage 返回使用次数最多的 N 条记录
 */
export function GetTopUsage(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(989274272, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUpdateState 获取当前更新器状态。当已探测到新版本时回填版本号与更新说明，
 * 否则 UI 只会拿到一个光秃秃的 "available" 状态而看不到任何内容。
 */
export function GetUpdateState(): $CancellablePromise<$models.UpdateStatus | null> {
    return $Call.ByID(2309909332).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetValue 读取键值
 */
export function GetValue(key: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3622336851, key).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetWebhookConfig 读取机器人通知配置（供前端设置页回填）
 */
export function GetWebhookConfig(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1054365561).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetWorkspace(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2311531739, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HideClipboardWindow 隐藏剪贴板独立窗口
 */
export function HideClipboardWindow(): $CancellablePromise<void> {
    return $Call.ByID(2624956500);
}

/**
 * HideNoteWindow 隐藏快捷笔记独立窗口（并复位置 noteMode 标志，保证热键开关正确）
 */
export function HideNoteWindow(): $CancellablePromise<void> {
    return $Call.ByID(218724534);
}

/**
 * HidePaletteWindow 隐藏命令面板窗口
 */
export function HidePaletteWindow(): $CancellablePromise<void> {
    return $Call.ByID(1149548777);
}

/**
 * HidePluginWindow 隐藏指定插件的窗口
 */
export function HidePluginWindow(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(1422908057, pluginID);
}

/**
 * HideWindow 隐藏主窗口
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(360771842);
}

/**
 * ImportPostman 导入 Postman Collection v2.1 JSON：在当前项目下创建请求。
 * 返回 (导入条数, 失败原因列表)。
 */
export function ImportPostman(jsonStr: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1405335199, jsonStr).then(($result: any) => {
        return $$createType1($result);
    });
}

export function InsertClipboardEntry(text: string, sourceApp: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2229753297, text, sourceApp).then(($result: any) => {
        return $$createType1($result);
    });
}

export function InstallPlugin(zipPath: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3107899418, zipPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * InstallPluginFromBytes 接受前端上传的文件字节安装插件（拖拽 fallback）
 */
export function InstallPluginFromBytes(fileName: string, fileData: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1056078213, fileName, fileData).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LaunchInstalledApp 启动指定路径的应用
 */
export function LaunchInstalledApp(path: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2257915428, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListAllItems 返回全部项目（命令面板前端拼音/子串匹配的全量池）
 */
export function ListAllItems(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3184161883).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListApiRequests 返回全部保存的请求。
 */
export function ListApiRequests(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2127003888).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListClipboardEntries(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2291752860, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListCollections(sceneID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1896706667, sceneID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDbConnections 返回全部连接，password 脱敏（返回空串，避免泄露）。
 */
export function ListDbConnections(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(260049081).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDbObjects 返回某个库下的表/视图结构（含字段），用于树展开时按需加载。
 */
export function ListDbObjects(id: string, dbName: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(101762196, id, dbName).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDbTree 返回连接下的库表/字段结构（SQL）或键列表（Redis），用于左侧浏览器树。
 */
export function ListDbTree(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1466340768, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHttpDocs 返回某项目下全部文档。
 */
export function ListHttpDocs(projectID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4032553293, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHttpEnvironments 返回某项目下全部环境。
 */
export function ListHttpEnvironments(projectID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3168261156, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHttpFolders 返回某项目下全部目录。
 */
export function ListHttpFolders(projectID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2583116027, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHttpHistory 返回某项目（projectID 为空=全部）最近 N 条请求历史。
 */
export function ListHttpHistory(projectID: string, limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4265925986, projectID, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHttpProjects 返回全部项目。
 */
export function ListHttpProjects(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4236670736).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListItems(collectionID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3764977142, collectionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListMonitorStats 汇总所有监控近 24h 在线率等指标
 */
export function ListMonitorStats(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4129737735).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListMonitors 列出全部监控
 */
export function ListMonitors(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(227707149).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListNotesTree 返回全部笔记节点（文件夹 + 文档），前端拼树。
 */
export function ListNotesTree(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3037949731).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListPluginExecLogs 返回最近 limit 条插件命令执行日志（前端历史展示，5.2）
 */
export function ListPluginExecLogs(limit: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1134931239, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListPlugins(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(442808626).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListScenes(workspaceID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3351845611, workspaceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListScheduledTasks 列出全部定时任务
 */
export function ListScheduledTasks(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1328995913).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSnapshots(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1489806735).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSnippets(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1439974928).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListTodos 列出所有待办
 */
export function ListTodos(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(443272331).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListTools(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1665311253).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListWorkspaces(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1048839064).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MinimizePluginWindow 最小化指定插件的窗口
 */
export function MinimizePluginWindow(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(3074352793, pluginID);
}

/**
 * MoveNoteNode 移动节点到新父目录（拖拽）。
 */
export function MoveNoteNode(id: string, newParentId: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(450057659, id, newParentId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * NotifyFocusComplete 专注计时结束时调用：发系统通知 + 机器人/webhook 推送。
 * title 为待办标题；minutes 为本次专注时长（分钟）。
 */
export function NotifyFocusComplete(title: string, minutes: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4203918042, title, minutes).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * NotifyFocusStart 专注开始时可选的提示（可选调用，不发 webhook，避免刷屏）。
 */
export function NotifyFocusStart(title: string, minutes: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3810333623, title, minutes).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OnClipboardChange handles clipboard change events
 */
export function OnClipboardChange(): $CancellablePromise<void> {
    return $Call.ByID(2121315099);
}

export function OpenAllInCollection(collectionID: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1237590910, collectionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenItem(item: db$0.CollectionItem): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(59138333, item).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PasteClipboardEntry 复制剪贴板条目并模拟 Ctrl+V 粘贴
 */
export function PasteClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2364851955, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PasteSnippet 将片段内容复制到剪贴板并粘贴
 */
export function PasteSnippet(content: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2289619634, content).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * QueryDbConnection 对已保存连接执行查询/命令，返回结果。
 */
export function QueryDbConnection(id: string, query: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1853863528, id, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RecordHttpRequestHistory 把一次请求+响应记录到历史（由 SendApiRequest 内部调用）。
 */
export function RecordHttpRequestHistory(input: $models.ApiRequestInput | null, resp: $models.ApiResponse | null): $CancellablePromise<void> {
    return $Call.ByID(3017044916, input, resp);
}

/**
 * RecordUsage 记录一次使用（跨窗口共享的 frecency 追踪）
 * key 格式：item:{id} | snippet:{id} | app:{name} | plugin:{pluginId}.{cmdId}
 */
export function RecordUsage(key: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(591933050, key).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RecordUsageEx 记录一次使用并附带展示信息（type/label/desc/input 用于「最近使用」直接展示与回放）
 */
export function RecordUsageEx(key: string, type_: string, label: string, desc: string, input: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3173203151, key, type_, label, desc, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RegisterPluginHostMethods 注入全部 Host API 实现。
 * 必须在 DB 就绪之后调用（db.* 依赖 a.DB），由 ServiceStartup 触发。
 */
export function RegisterPluginHostMethods(): $CancellablePromise<void> {
    return $Call.ByID(1217370176);
}

/**
 * RenameNoteNode 重命名文件夹/文档。
 */
export function RenameNoteNode(id: string, name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1779470256, id, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReorderApiRequests 重排/移动请求（拖拽排序与跨目录、跨项目移动）。
 */
export function ReorderApiRequests(projectID: string, folderID: string, ids: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(445442977, projectID, folderID, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderCollections(orderedIDs: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1456313334, orderedIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReorderHttpFolders 重排/移动目录（拖拽排序与跨目录、跨项目移动）。
 * 跨项目移动时递归修正整棵子树的 project_id，避免孤儿数据。
 */
export function ReorderHttpFolders(projectID: string, parentID: string, ids: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3187448314, projectID, parentID, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderItems(orderedIDs: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1523637631, orderedIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderScenes(orderedIDs: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4156556976, orderedIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderWorkspaces(orderedIDs: string[]): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3135663759, orderedIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetInstalledAppsCache 清除应用缓存（下次搜索时重新扫描）
 */
export function ResetInstalledAppsCache(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(421562045).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RestartApp 下载完成后拉起 NSIS 安装器以完成更新。
 * 
 * 流程：Updater.DownloadAndInstall 已把安装器下载并验签到本地临时路径（通过 DownloadedPath 取得），
 * 这里直接拉起安装器（非静默，展示安装向导）。安装器的 .onInit 阶段会 taskkill 仍在运行的
 * quickdock.exe，向导完成后提供"运行 QuickDock"勾选项，用户点完成即可重新打开应用。
 * 
 * 安装器用 DETACHED_PROCESS 脱离主程序作业对象独立存活——否则主程序退出时作业对象会连带杀掉它，
 * 向导就弹不出来了。同时先打上"真退出"标记（PrepareQuitFn），让主窗口的 WindowClosing 钩子放行，
 * 主程序走"退出"路径干净清理，再由安装器覆盖文件。
 */
export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(1949245344);
}

export function RestoreSnapshot(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2330421416, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ResumeHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(469208180);
}

/**
 * RevealInExplorer 在文件资源管理器中定位目标路径（目录直接打开，文件高亮选中）
 */
export function RevealInExplorer(path: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1746858135, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RunScheduledTaskNow 立即手动执行一次（不影响下次排期）
 */
export function RunScheduledTaskNow(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2518119461, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveDbConnection 新建或更新连接。密码明文入参，落库前 DPAPI 加密。
 */
export function SaveDbConnection(input: $models.DbConnectionInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1059024145, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveNote 保存快捷笔记内容（整段防抖保存，upsert 固定关键词片段）
 */
export function SaveNote(content: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(535265659, content).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveUrlAsItem 将剪贴板中的 URL 保存为网页项目（命令面板智能路由用）
 */
export function SaveUrlAsItem(rawURL: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2571322723, rawURL).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ScanInstalledApps 扫描已安装应用（缓存，首次调用后复用）
 */
export function ScanInstalledApps(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2397186455).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SearchAll 跨全部工作空间搜索项目（使用 FTS5）
 */
export function SearchAll(query: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1354570973, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SearchNotesTree 按名称/内容/标签搜索笔记节点。
 */
export function SearchNotesTree(q: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2068972087, q).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SearchSnippets(query: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1489427676, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SelectAndInstallPlugin 打开原生文件对话框选择 .zip 并安装
 */
export function SelectAndInstallPlugin(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(910879761).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SendApiRequest 执行一次请求并返回响应（不保存）。
 * 发送前应用项目共享头 + 环境变量（{{var}} 替换），请求头覆盖项目头同名 key。
 */
export function SendApiRequest(input: $models.ApiRequestInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1133039205, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SendTestNotification 发送一条测试通知（前端「发送测试提醒」按钮调用）
 */
export function SendTestNotification(title: string, body: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2317317471, title, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetApp 设置 App 引用（由 main.go 在创建后调用）
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3735478509, app);
}

export function SetAutoStart(enabled: boolean): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1650346907, enabled).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetClipboardHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2903533492, modifiers, vk).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetClipboardRetentionDays(days: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3284935865, days).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3895446934, modifiers, vk).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetMonitorEnabled 启用/停用监控
 */
export function SetMonitorEnabled(id: string, enabled: boolean): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(575565977, id, enabled).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetNoteHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3071218858, modifiers, vk).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetPaletteHotkeyConfig(modifiers: number, vk: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(189880149, modifiers, vk).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetPendingPluginInit 保存待注入的初始文本和命令（从命令面板跨窗口传递）
 */
export function SetPendingPluginInit(text: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(4124006564, text, command);
}

/**
 * SetScheduledTaskEnabled 启用/停用定时任务；启用时重算 next_run
 */
export function SetScheduledTaskEnabled(id: string, enabled: boolean): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2943277933, id, enabled).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetSyncConfig 保存统一同步配置。
 */
export function SetSyncConfig(cfg: sync$0.Config | null): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1319724007, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetTodoStatus 设置待办状态（看板拖拽）
 */
export function SetTodoStatus(id: string, status: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3043231880, id, status).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetValue 写入键值
 */
export function SetValue(key: string, value: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3540985191, key, value).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetWebhookConfig 保存机器人通知配置。
 */
export function SetWebhookConfig(dingtalk: string, wecom: string, feishu: string, serverchan: string, pushplus: string, telegram: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1035468701, dingtalk, wecom, feishu, serverchan, pushplus, telegram).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ShowPluginWindow 在面板中显示插件窗口（任务栏隐藏）
 */
export function ShowPluginWindow(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(3008209844, pluginID);
}

/**
 * SkipUpdate 跳过指定版本的更新
 */
export function SkipUpdate(version: string): $CancellablePromise<void> {
    return $Call.ByID(358606692, version);
}

/**
 * StartAIStreamServer 启动本地流式服务（绑定 127.0.0.1:0 随机端口）
 */
export function StartAIStreamServer(): $CancellablePromise<void> {
    return $Call.ByID(1302344967);
}

/**
 * StartAutoUpdateChecker 启动后台定时检查（取代 Wails 内置的 CheckInterval 自动下载）。
 * 
 * 为什么不用 Wails 的 CheckInterval：它的周期检查走 CheckAndInstall —— 会自动把安装包
 * 下载并暂存，但永远不会主动重启应用（Restart 仅由 Wails 内置窗口的"重启"按钮触发，而
 * 我们用的是自定义 UI，不挂内置窗口）。结果就是自动下载了一堆安装包却永远不生效，且与手动
 * "检测更新"的下载/重启路径完全脱节。
 * 
 * 这里只做"检查 + 通知"：发现新版本后通过 quickdock:update:status 事件把同一份 UpdateStatus
 * 推给前端，复用 SettingsModal 里手动检测那套 UI 与下载/重启逻辑，两条路径完全一致。
 */
export function StartAutoUpdateChecker(): $CancellablePromise<void> {
    return $Call.ByID(1066583199);
}

/**
 * StartMonitorChecker 启动网站监控检查器（仿 UptimeRobot）。
 * 同样采用精确定时器：每次检测后按 interval 计算最近待检监控的等待时长并精确 sleep，
 * 监控增删改/启停时用 monitorWake 立即唤醒重排。
 */
export function StartMonitorChecker(): $CancellablePromise<void> {
    return $Call.ByID(3149802367);
}

/**
 * StartReminderScheduler 启动待办定时提醒调度器（常驻 goroutine）
 * 每 10 秒轮询一次，对「已到提醒时间、未完成、未发送」的待办推送系统通知。
 */
export function StartReminderScheduler(): $CancellablePromise<void> {
    return $Call.ByID(83997965);
}

/**
 * StartScheduleRunner 启动定时任务调度器。
 * 采用「精确定时器」而非固定 10s 轮询：每次执行后计算最近的 next_run，
 * 用 time.Timer 精确 sleep 到该时刻（秒级精度，不再有最多 10s 的延迟触发），
 * 任务被增删改/启停时用 schedWake 立即唤醒重排。这正是调度库内部的核心机制，
 * 但无需引入额外依赖，且与进程内状态天然一致。
 */
export function StartScheduleRunner(): $CancellablePromise<void> {
    return $Call.ByID(3855636353);
}

/**
 * StopAIStreamServer 关闭本地流式服务（应用退出时调用）
 */
export function StopAIStreamServer(): $CancellablePromise<void> {
    return $Call.ByID(4164354063);
}

export function SuspendHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(1551644173);
}

/**
 * SyncDeleteBackup 删除当前同步后端上的指定备份文件。
 */
export function SyncDeleteBackup(filename: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(81959348, filename).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncDownloadAndRestore 从当前同步后端下载指定备份并恢复到数据库。
 */
export function SyncDownloadAndRestore(filename: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2176401504, filename).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncExportBackup 导出当前数据并上传到当前同步后端。
 */
export function SyncExportBackup(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3490490185).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncListBackends 返回所有可用的同步后端类型（供 UI 渲染选择器）。
 */
export function SyncListBackends(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(189707712).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncListBackups 列出当前同步后端上的备份文件。
 */
export function SyncListBackups(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2443003336).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncTestConnection 测试当前同步后端连接。
 */
export function SyncTestConnection(): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3450726065).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestDbConnection 用传入配置（未保存也可）测试连通性。
 */
export function TestDbConnection(input: $models.DbConnectionInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3568775036, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestWebhook 向指定平台的 Webhook 地址发送一条测试消息（保存前即可验证配置是否正确）。
 * kind: dingtalk | wecom | feishu | serverchan | pushplus | telegram
 */
export function TestWebhook(kind: string, url: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3897684719, kind, url).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ToggleMaximizePluginWindow 切换指定插件的窗口最大化/还原
 */
export function ToggleMaximizePluginWindow(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(31433991, pluginID);
}

export function TogglePinClipboardEntry(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1629693783, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ToggleTodo 切换完成状态
 */
export function ToggleTodo(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2390775654, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UninstallPlugin(id: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3980100571, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateApiRequest 更新已有请求（按 ID）。
 */
export function UpdateApiRequest(id: string, input: $models.ApiRequestInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1614439578, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateClipboardNote 更新剪贴板条目的备注
 */
export function UpdateClipboardNote(id: string, note: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(649690399, id, note).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateCollection(id: string, updates: { [_ in string]?: any }): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2047807399, id, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateDbRow 以主键定位单行并提交修改（参数化，标识符按库类型安全引用）。
 */
export function UpdateDbRow(id: string, input: $models.DbRowUpdateInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2326769535, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateHttpDoc 更新文档（仅名称/内容）。
 */
export function UpdateHttpDoc(id: string, input: $models.HttpDocInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3618921491, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateHttpEnvironment 更新环境。
 */
export function UpdateHttpEnvironment(id: string, input: $models.HttpEnvInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3142715104, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateHttpFolder 更新目录（仅名称/父级/排序）。
 */
export function UpdateHttpFolder(id: string, input: $models.HttpFolderInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3091790803, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateHttpProject 更新项目。
 */
export function UpdateHttpProject(id: string, input: $models.HttpProjectInput): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(324333044, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateItem(id: string, updates: { [_ in string]?: any }): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3624550944, id, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateMonitor 更新监控配置
 */
export function UpdateMonitor(m: db$0.Monitor): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(832428983, m).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateNoteDoc 更新文档内容与标签。tags 为 JSON 数组字符串（留空则清空）。
 */
export function UpdateNoteDoc(id: string, content: string, tags: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(2624204355, id, content, tags).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateScene(id: string, updates: { [_ in string]?: any }): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(688719653, id, updates).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateScheduledTask 更新定时任务并重算 next_run
 */
export function UpdateScheduledTask(t: db$0.ScheduledTask): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(810797915, t).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateSnippet(id: string, keyword: string, content: string, category: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4118751660, id, keyword, content, category).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateTodo 更新待办（含起止时间、提醒时间、标签、重复配置与状态）
 */
export function UpdateTodo(id: string, title: string, priority: string, dueDate: string, note: string, startTime: string, endTime: string, reminderTime: string, recurrence: string, tags: string, status: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(3979953559, id, title, priority, dueDate, note, startTime, endTime, reminderTime, recurrence, tags, status).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateTool(id: string, name: string, toolType: string, path: string, args: string, isDefault: number): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(4031419249, id, name, toolType, path, args, isDefault).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateWorkspace(id: string, name: string): $CancellablePromise<$models.ApiResult | null> {
    return $Call.ByID(1525445244, id, name).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ApiResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.UpdateStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.ApiRequestInput.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
