// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig 兼容旧接口的单一配置（API Key 已解密）
 */
export class AIConfig {
    "provider": string;
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "temperature": number;
    "maxTokens": number;

    /** Creates a new AIConfig instance. */
    constructor($$source: Partial<AIConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConfig($$parsedSource as Partial<AIConfig>);
    }
}

/**
 * AIProfile 一个完整的 AI 配置档案（含 API Key，前端回填时为明文）
 */
export class AIProfile {
    "id": string;
    "name": string;
    "provider": string;
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "temperature": number;
    "maxTokens": number;
    "systemPrompt": string;
    "topP": number;
    "frequencyPenalty": number;
    "presencePenalty": number;
    "thinkingEnabled": boolean;

    /** Creates a new AIProfile instance. */
    constructor($$source: Partial<AIProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }
        if (!("topP" in $$source)) {
            this["topP"] = 0;
        }
        if (!("frequencyPenalty" in $$source)) {
            this["frequencyPenalty"] = 0;
        }
        if (!("presencePenalty" in $$source)) {
            this["presencePenalty"] = 0;
        }
        if (!("thinkingEnabled" in $$source)) {
            this["thinkingEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProfile($$parsedSource as Partial<AIProfile>);
    }
}

/**
 * AISaveProfilesRequest 保存档案列表的请求
 */
export class AISaveProfilesRequest {
    "active": string;
    "profiles": AIProfile[];

    /** Creates a new AISaveProfilesRequest instance. */
    constructor($$source: Partial<AISaveProfilesRequest> = {}) {
        if (!("active" in $$source)) {
            this["active"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISaveProfilesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AISaveProfilesRequest {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        return new AISaveProfilesRequest($$parsedSource as Partial<AISaveProfilesRequest>);
    }
}

/**
 * ApiRequestInput 前端传入的请求（新建/更新/发送共用）。
 * Headers 为 JSON map 字符串；Auth 信息仅本地保存，发送时按类型注入。
 */
export class ApiRequestInput {
    "id": string;
    "name": string;
    "projectId": string;
    "folderId": string;
    "environmentId": string;
    "method": string;
    "url": string;
    "headers": string;
    "body": string;
    "bodyType": string;
    "authType": string;
    "authToken": string;
    "authUser": string;
    "authPass": string;
    "sort": number;

    /** Creates a new ApiRequestInput instance. */
    constructor($$source: Partial<ApiRequestInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = "";
        }
        if (!("environmentId" in $$source)) {
            this["environmentId"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("bodyType" in $$source)) {
            this["bodyType"] = "";
        }
        if (!("authType" in $$source)) {
            this["authType"] = "";
        }
        if (!("authToken" in $$source)) {
            this["authToken"] = "";
        }
        if (!("authUser" in $$source)) {
            this["authUser"] = "";
        }
        if (!("authPass" in $$source)) {
            this["authPass"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiRequestInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ApiRequestInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApiRequestInput($$parsedSource as Partial<ApiRequestInput>);
    }
}

/**
 * ApiResponse 发送结果（不落库）。
 */
export class ApiResponse {
    "status": number;
    "ok": boolean;
    "headers": { [_ in string]?: string };
    "body": string;
    "durationMs": number;
    "size": number;
    "truncated": boolean;

    /** Creates a new ApiResponse instance. */
    constructor($$source: Partial<ApiResponse> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ApiResponse {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new ApiResponse($$parsedSource as Partial<ApiResponse>);
    }
}

/**
 * ApiResult 统一 API 返回结构
 * code: 0=成功, 1=失败
 */
export class ApiResult {
    "code": number;
    "data": any;
    "msg": string;

    /** Creates a new ApiResult instance. */
    constructor($$source: Partial<ApiResult> = {}) {
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApiResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApiResult($$parsedSource as Partial<ApiResult>);
    }
}

/**
 * DbConnectionInput 前端传入的连接配置。password 为明文，落库前由本层用 DPAPI 加密。
 */
export class DbConnectionInput {
    "id": string;
    "name": string;
    "dbType": string;
    "host": string;
    "port": number;
    "username": string;

    /**
     * 明文；空表示不修改（更新时保留原值）
     */
    "password": string;
    "database": string;
    "filePath": string;

    /** Creates a new DbConnectionInput instance. */
    constructor($$source: Partial<DbConnectionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dbType" in $$source)) {
            this["dbType"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DbConnectionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DbConnectionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DbConnectionInput($$parsedSource as Partial<DbConnectionInput>);
    }
}

/**
 * DbRowUpdateInput 前端提交的单行修改：以主键定位行，Sets 为列→新值，Nulls 为需置 NULL 的列。
 */
export class DbRowUpdateInput {
    "tableName": string;
    "pkColumn": string;
    "pkValue": string;
    "sets": { [_ in string]?: string };
    "nulls": string[];

    /** Creates a new DbRowUpdateInput instance. */
    constructor($$source: Partial<DbRowUpdateInput> = {}) {
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("pkColumn" in $$source)) {
            this["pkColumn"] = "";
        }
        if (!("pkValue" in $$source)) {
            this["pkValue"] = "";
        }
        if (!("sets" in $$source)) {
            this["sets"] = {};
        }
        if (!("nulls" in $$source)) {
            this["nulls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DbRowUpdateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DbRowUpdateInput {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField3_0($$parsedSource["sets"]);
        }
        if ("nulls" in $$parsedSource) {
            $$parsedSource["nulls"] = $$createField4_0($$parsedSource["nulls"]);
        }
        return new DbRowUpdateInput($$parsedSource as Partial<DbRowUpdateInput>);
    }
}

/**
 * HttpDocInput 目录下的 Markdown 文档（新建/更新共用）。
 */
export class HttpDocInput {
    "id": string;
    "projectId": string;
    "folderId": string;
    "name": string;
    "content": string;
    "sort": number;

    /** Creates a new HttpDocInput instance. */
    constructor($$source: Partial<HttpDocInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpDocInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HttpDocInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpDocInput($$parsedSource as Partial<HttpDocInput>);
    }
}

export class HttpEnvInput {
    "id": string;
    "projectId": string;
    "name": string;
    "variables": string;
    "sort": number;

    /** Creates a new HttpEnvInput instance. */
    constructor($$source: Partial<HttpEnvInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("variables" in $$source)) {
            this["variables"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpEnvInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HttpEnvInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpEnvInput($$parsedSource as Partial<HttpEnvInput>);
    }
}

export class HttpFolderInput {
    "id": string;
    "projectId": string;
    "parentId": string;
    "name": string;
    "sort": number;

    /** Creates a new HttpFolderInput instance. */
    constructor($$source: Partial<HttpFolderInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpFolderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HttpFolderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpFolderInput($$parsedSource as Partial<HttpFolderInput>);
    }
}

/**
 * HttpProjectInput / HttpEnvInput 项目与环境（Postman 式分组）。
 */
export class HttpProjectInput {
    "id": string;
    "name": string;
    "headers": string;
    "sort": number;

    /** Creates a new HttpProjectInput instance. */
    constructor($$source: Partial<HttpProjectInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpProjectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HttpProjectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpProjectInput($$parsedSource as Partial<HttpProjectInput>);
    }
}

/**
 * UpdateStatus 返回给前端的更新状态
 */
export class UpdateStatus {
    "currentVersion": string;

    /**
     * idle / checking / available / up-to-date / downloading / ready / error
     */
    "state": string;
    "availableVersion"?: string;
    "releaseNotes"?: string;

    /**
     * 0-100
     */
    "downloadProgress"?: number;
    "error"?: string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}

// Private type creation functions
const $$createType0 = AIProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
