// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CollectionItem 项目
 */
export class CollectionItem {
    "id": string;
    "workspaceId": string;
    "collectionId": string;
    "name": string;
    "type": string;
    "value": string;
    "workingDirectory": string;
    "toolId": string;
    "tool": string;
    "args": string;
    "icon": string;
    "color": string;
    "remark": string;
    "pluginData": string;
    "usageCount": number;
    "sort": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new CollectionItem instance. */
    constructor($$source: Partial<CollectionItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("toolId" in $$source)) {
            this["toolId"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = "";
        }
        if (!("usageCount" in $$source)) {
            this["usageCount"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectionItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectionItem($$parsedSource as Partial<CollectionItem>);
    }
}

/**
 * Monitor 网站运行状态监控（仿 UptimeRobot）
 * expected_status 支持 "2xx"/"3xx"/"4xx"/"5xx" 或精确码如 "200"
 */
export class Monitor {
    "id": string;
    "name": string;
    "url": string;

    /**
     * GET/POST/HEAD...
     */
    "method": string;

    /**
     * 检测间隔（秒）
     */
    "intervalSec": number;

    /**
     * 单次请求超时（秒）
     */
    "timeoutSec": number;

    /**
     * 2xx | 3xx | 4xx | 5xx | 200 ...
     */
    "expectedStatus": string;
    "followRedirects": boolean;
    "enabled": boolean;
    "notifyDown": boolean;
    "notifyUp": boolean;

    /**
     * up | down | ''
     */
    "lastStatus": string;

    /**
     * YYYY-MM-DD HH:MM:SS
     */
    "lastCheckedAt": string;

    /**
     * unix 秒，供检查器精确计算间隔
     */
    "lastCheckedTs": number;
    "lastLatencyMs": number;
    "lastStatusCode": number;
    "lastError": string;

    /**
     * 忽略证书错误（自签名/过期等），仅单条生效，默认关闭
     */
    "skipTLSVerify": boolean;

    /**
     * SSL 证书提前 N 天告警
     */
    "certWarnDays": number;

    /**
     * 证书过期时间（unix 秒，0=未知/非HTTPS）
     */
    "certExpiresAt": number;

    /**
     * 上次证书告警时间（unix 秒，去抖）
     */
    "lastCertWarned": number;

    /**
     * none | contains | not_contains | regex
     */
    "contentMatchType": string;
    "contentMatchPattern": string;

    /**
     * 误报抑制：连续 N 次失败才发宕机告警（>=1）
     */
    "downAlertThreshold": number;

    /**
     * 当前连续失败次数（运行态，>=0）
     */
    "consecutiveDown": number;
    "sort": number;
    "createdAt": string;

    /** Creates a new Monitor instance. */
    constructor($$source: Partial<Monitor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("intervalSec" in $$source)) {
            this["intervalSec"] = 0;
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("expectedStatus" in $$source)) {
            this["expectedStatus"] = "";
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("notifyDown" in $$source)) {
            this["notifyDown"] = false;
        }
        if (!("notifyUp" in $$source)) {
            this["notifyUp"] = false;
        }
        if (!("lastStatus" in $$source)) {
            this["lastStatus"] = "";
        }
        if (!("lastCheckedAt" in $$source)) {
            this["lastCheckedAt"] = "";
        }
        if (!("lastCheckedTs" in $$source)) {
            this["lastCheckedTs"] = 0;
        }
        if (!("lastLatencyMs" in $$source)) {
            this["lastLatencyMs"] = 0;
        }
        if (!("lastStatusCode" in $$source)) {
            this["lastStatusCode"] = 0;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("skipTLSVerify" in $$source)) {
            this["skipTLSVerify"] = false;
        }
        if (!("certWarnDays" in $$source)) {
            this["certWarnDays"] = 0;
        }
        if (!("certExpiresAt" in $$source)) {
            this["certExpiresAt"] = 0;
        }
        if (!("lastCertWarned" in $$source)) {
            this["lastCertWarned"] = 0;
        }
        if (!("contentMatchType" in $$source)) {
            this["contentMatchType"] = "";
        }
        if (!("contentMatchPattern" in $$source)) {
            this["contentMatchPattern"] = "";
        }
        if (!("downAlertThreshold" in $$source)) {
            this["downAlertThreshold"] = 0;
        }
        if (!("consecutiveDown" in $$source)) {
            this["consecutiveDown"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Monitor instance from a string or object.
     */
    static createFrom($$source: any = {}): Monitor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Monitor($$parsedSource as Partial<Monitor>);
    }
}

/**
 * ScheduledTask 定时任务
 * 动作(action)：app=打开软件/文件  dir=打开目录  url=打开网页  command=执行命令  http=HTTP 请求
 * 调度(scheduleKind)：once=一次性  interval=固定间隔  daily=每天  weekly=每周
 */
export class ScheduledTask {
    "id": string;
    "name": string;

    /**
     * app | dir | url | command | http
     */
    "action": string;

    /**
     * 路径 / 网址 / 命令 / http url
     */
    "target": string;

    /**
     * app/command 的工作目录
     */
    "workingDir": string;

    /**
     * GET/POST/...
     */
    "httpMethod": string;

    /**
     * 每行 "Key: Value"
     */
    "httpHeaders": string;
    "httpBody": string;

    /**
     * once | interval | daily | weekly
     */
    "scheduleKind": string;

    /**
     * once：YYYY-MM-DD HH:MM:SS
     */
    "runAt": string;

    /**
     * interval：间隔秒数
     */
    "intervalSec": number;

    /**
     * daily/weekly：HH:MM:SS
     */
    "timeOfDay": string;

    /**
     * weekly：CSV，0=周日..6=周六
     */
    "weekdays": string;
    "enabled": boolean;

    /**
     * 执行后是否发系统通知
     */
    "notify": boolean;

    /**
     * 下次运行 YYYY-MM-DD HH:MM:SS（'' 表示不再运行）
     */
    "nextRun": string;

    /**
     * 上次运行 YYYY-MM-DD HH:MM:SS
     */
    "lastRun": string;

    /**
     * ok | fail | ''
     */
    "lastStatus": string;

    /**
     * 上次运行简要结果
     */
    "lastResult": string;
    "sort": number;
    "createdAt": string;

    /** Creates a new ScheduledTask instance. */
    constructor($$source: Partial<ScheduledTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("httpMethod" in $$source)) {
            this["httpMethod"] = "";
        }
        if (!("httpHeaders" in $$source)) {
            this["httpHeaders"] = "";
        }
        if (!("httpBody" in $$source)) {
            this["httpBody"] = "";
        }
        if (!("scheduleKind" in $$source)) {
            this["scheduleKind"] = "";
        }
        if (!("runAt" in $$source)) {
            this["runAt"] = "";
        }
        if (!("intervalSec" in $$source)) {
            this["intervalSec"] = 0;
        }
        if (!("timeOfDay" in $$source)) {
            this["timeOfDay"] = "";
        }
        if (!("weekdays" in $$source)) {
            this["weekdays"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("notify" in $$source)) {
            this["notify"] = false;
        }
        if (!("nextRun" in $$source)) {
            this["nextRun"] = "";
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = "";
        }
        if (!("lastStatus" in $$source)) {
            this["lastStatus"] = "";
        }
        if (!("lastResult" in $$source)) {
            this["lastResult"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduledTask instance from a string or object.
     */
    static createFrom($$source: any = {}): ScheduledTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduledTask($$parsedSource as Partial<ScheduledTask>);
    }
}
