// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webdav$0 from "../webdav/models.js";

/**
 * Config 统一同步配置：指定当前启用的后端类型及其专属配置。
 * 新增后端时只需在此增加对应字段（如 Git *GitConfig、S3 *S3Config），
 * 上层逻辑无需改动。
 */
export class Config {
    /**
     * Type 当前启用的后端类型："webdav" / ""(未启用)。
     */
    "type": string;

    /**
     * WebDAV 当 Type=="webdav" 时有效。
     */
    "webdav": webdav$0.Config;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("webdav" in $$source)) {
            this["webdav"] = (new webdav$0.Config());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webdav" in $$parsedSource) {
            $$parsedSource["webdav"] = $$createField1_0($$parsedSource["webdav"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

// Private type creation functions
const $$createType0 = webdav$0.Config.createFrom;
